# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: Carlos' Portfolio

# Uncomment the lines below to configure your website in a second language.
es:
  languageCode: es-pa
  contentDir: content/es
  title: Portfolio de Carlos
  params:
    description: Site description in English...
  menu:
    main:
      - name: "Sobre mí"
        url: '#about'
        weight: 1
